# Generated by Django 4.1.1 on 2022-10-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='task_title_detail',
            field=models.BooleanField(blank=True, default=True, verbose_name='Реквизиты задачи'),
        ),
    ]
