# Generated by Django 4.1.1 on 2022-10-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstype',
            name='comment',
            field=models.CharField(default='', max_length=255, verbose_name='Комментарии'),
        ),
    ]
